### PR TITLE
Logging Changes

### PR DESCRIPTION
**Pull request by kaustubha-m**
Logging Changes

### CODE REVIEW

**Comment by codewnw** [comment]
@gitk21  Please resolve the merge conflicts. I have recently checked-in password hashing code.

**Comment by kaustubha-m** [comment]
Sir, I have resolved conflicts

**Comment by codewnw** [comment]
One more PR has been merged so looks like you PR again got few conflicts. Please resolve those also.

**Comment by kaustubha-m** [comment]
Sir, Resolved Conflicts

**Comment by kaustubha-m** [comment]
Sir, One more conflict appeared. Now Resolved

**Review by codewnw — APPROVED** [review]

**Pull request merged**
